version: "3"
services:
  manager:
    container_name: manager
    build:
      context: .
    env_file:
      - ../../../shared/robokop.env
    environment:
      - ROBOKOP_HOME=/home/murphy
      - CELERY_BROKER_URL=amqp://${BROKER_USER}:${BROKER_PASSWORD}@${BROKER_HOST}:${BROKER_PORT}/manager
      - CELERY_RESULT_BACKEND=redis://:${RESULTS_PASSWORD}@${RESULTS_HOST}:${RESULTS_PORT}/${MANAGER_RESULTS_DB}
      - SUPERVISOR_PORT=${MANAGER_SUPERVISOR_PORT}
      - PYTHONPATH=/home/murphy/robokop
    ports:
      - "${MANAGER_PORT}:${MANAGER_PORT}"
      - "${MANAGER_SUPERVISOR_PORT}:${MANAGER_SUPERVISOR_PORT}"
    volumes:
      - ../../../logs:/home/murphy/logs
      - ../../../shared:/home/murphy/shared
      - ../..:/home/murphy/robokop
