version: "3"
services:
  manager:
    container_name: viewer
    build:
      context: ../..
      dockerfile: deploy/manager/Dockerfile
    env_file:
      - ../../shared/robokop.env
    environment:
      - ROBOKOP_HOME=/home/murphy
      - PYTHONPATH=/home/murphy/robokop-viewer
    ports:
      - "${MANAGER_PORT}:${MANAGER_PORT}"
    volumes:
      - ../../logs:/home/murphy/logs
      - ../../shared:/home/murphy/shared
