name: robokop
dependencies:
- python=3.6
- pip
- pip:
  - bcrypt
  - eventlet
  - flask
  - flask-security
  - flask-restplus
  - gunicorn
  - kombu
  - lru-dict
  - numpy>=1.8.0
  - pytest
  
  # this may be interesting to explore:
  # https://conda.io/docs/user-guide/tasks/manage-environments.html#saving-environment-variables